"""Emit the LaTeX Defrise result-table rows straight from the evaluation JSON.

Standalone port of the ``defrise_table`` function in the paper's private
``make_tables.py``, which also handles the engine and camera datasets and so
cannot run without their private result files. This script needs only
``results/defrise_bgnr/``, which ships with this repository.

    python make_defrise_table.py
    python make_defrise_table.py --write
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
RESULTS = REPO_ROOT / "results" / "defrise_bgnr"

DEFRISE_ORDER = [
    "sart", "dart", "asdpocs", "bgdr_dart_support",
    "bgdr_dilated_support", "bgdr_carved_hull",
    "bgdr_carved_hull_box", "bgdr_oracle_support",
]
DEFRISE_LABEL = {
    "sart": "SART",
    "dart": "DART",
    "asdpocs": "ASD-POCS",
    "bgdr_dart_support": "BGDR, DART support",
    "bgdr_dilated_support": "\\quad dilated support",
    "bgdr_carved_hull": "\\quad silhouette hull",
    "bgdr_carved_hull_box": "\\quad silhouette hull + box",
    "bgdr_oracle_support": "\\quad oracle support",
}
DEFRISE_METRICS = [
    ("foreground_mse", "{:.3e}", "{:.1e}", "min"),
    ("bbox_ssim", "{:.4f}", "{:.1e}", "max"),
    ("boundary_hfen", "{:.4f}", "{:.1e}", "min"),
    ("far_background_mse", "{:.3e}", "{:.1e}", "min"),
    ("residual", "{:.5f}", "{:.1e}", "min"),
]


def _mean_sd(values: list[float], mean_fmt: str, sd_fmt: str) -> str:
    """Render a mean and sample SD without silently treating three seeds as exact."""
    mean = statistics.fmean(values)
    sd = statistics.stdev(values) if len(values) > 1 else 0.0
    return f"{mean_fmt.format(mean)} $\\pm$ {sd_fmt.format(sd)}"


def defrise_table(payload: dict, seed_payloads: list[dict]) -> str:
    """Exact-reference table generated from the committed three-seed aggregate."""
    aggregate = payload["aggregate"]
    support_by_seed = []
    for seed in seed_payloads:
        rows = {row["method"]: row for row in seed["rows"]}
        support_by_seed.append({
            method: rows[method]["support"]["containment"]
            for method in rows if "support" in rows[method]
        })
    containment_source = {
        "dart": "bgdr_dart_support",
        "bgdr_dart_support": "bgdr_dart_support",
        "bgdr_dilated_support": "bgdr_dilated_support",
        "bgdr_carved_hull": "bgdr_carved_hull",
        "bgdr_carved_hull_box": "bgdr_carved_hull_box",
        "bgdr_oracle_support": "bgdr_oracle_support",
    }
    practical = [method for method in DEFRISE_ORDER
                 if method != "bgdr_oracle_support"]
    best = {
        metric: (min if direction == "min" else max)(
            aggregate[method][metric]["mean"] for method in practical
        )
        for metric, _, _, direction in DEFRISE_METRICS
    }
    lines = []
    for method in DEFRISE_ORDER:
        source = containment_source.get(method)
        if source is None:
            containment = "--"
        else:
            values = [100.0 * seed[source] for seed in support_by_seed]
            containment = _mean_sd(values, "{:.2f}", "{:.3f}")
        cells = [containment]
        for metric, mean_fmt, sd_fmt, _ in DEFRISE_METRICS:
            values = aggregate[method][metric]["values"]
            rendered = _mean_sd(values, mean_fmt, sd_fmt)
            if (method != "bgdr_oracle_support"
                    and abs(aggregate[method][metric]["mean"] - best[metric]) < 1e-12):
                rendered = f"\\textbf{{{rendered}}}"
            cells.append(rendered)
        lines.append(f"{DEFRISE_LABEL[method]} & " + " & ".join(cells) + " \\\\")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results-dir", type=Path, default=RESULTS)
    parser.add_argument("--write", action="store_true",
                        help="write tab_defrise_rows.tex next to this script's output dir")
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "content")
    args = parser.parse_args()

    payload_path = args.results_dir / "defrise_results.json"
    if not payload_path.exists():
        raise SystemExit(f"missing {payload_path}")
    payload = json.loads(payload_path.read_text())
    seed_payloads = [
        json.loads((args.results_dir / Path(path).name).read_text())
        for path in payload["seed_result_files"]
    ]

    rows = defrise_table(payload, seed_payloads)
    print(rows)

    if args.write:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        stamp = (
            "% Generated by code/make_defrise_table.py from "
            "results/defrise_bgnr/defrise_results.json -- do not edit by hand.\n"
        )
        out = args.output_dir / "tab_defrise_rows.tex"
        out.write_text(stamp + rows + "\n")
        print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
